#!/bin/bash
#
# Buildkite Agent Setup Script for Kernelbot
#
# This script configures a Buildkite agent for a single GPU with proper isolation.
# Each GPU on the node should have its own agent with dedicated resources.
#
# Usage:
#   sudo ./setup-agent.sh <gpu_index> <queue_name> [memory_limit] [cpu_cores]
#
# Examples:
#   sudo ./setup-agent.sh 0 nvidia-h100-0 32G 16
#   sudo ./setup-agent.sh 1 nvidia-h100-1 32G 16
#
# Prerequisites:
#   - Buildkite agent installed: https://buildkite.com/docs/agent/v3/installation
#   - Docker installed with NVIDIA runtime
#   - BUILDKITE_AGENT_TOKEN set in environment or passed via config
#
# What this script does:
#   1. Creates a systemd service for the agent bound to specific GPU
#   2. Creates a cgroup slice for CPU/RAM isolation
#   3. Configures agent with queue tags for job routing
#

set -euo pipefail

# Parse arguments
GPU_INDEX="${1:?GPU index required (e.g., 0, 1, 2...)}"
QUEUE_NAME="${2:?Queue name required (e.g., nvidia-h100-0)}"
MEMORY_LIMIT="${3:-32G}"
CPU_CORES="${4:-16}"

# Validate GPU exists
if ! nvidia-smi -i "$GPU_INDEX" &>/dev/null; then
    echo "Error: GPU $GPU_INDEX not found"
    nvidia-smi -L
    exit 1
fi

echo "Setting up Buildkite agent for GPU $GPU_INDEX with queue $QUEUE_NAME"
echo "  Memory limit: $MEMORY_LIMIT"
echo "  CPU cores: $CPU_CORES"

# Create buildkite user if it doesn't exist
if ! id buildkite &>/dev/null; then
    echo "Creating buildkite user..."
    useradd -r -m -s /bin/bash buildkite
    usermod -aG docker buildkite
fi

# Create agent config directory
AGENT_CONFIG_DIR="/etc/buildkite-agent/agent-${GPU_INDEX}"
mkdir -p "$AGENT_CONFIG_DIR"

# Create agent configuration file
cat > "$AGENT_CONFIG_DIR/buildkite-agent.cfg" << EOF
# Buildkite Agent Configuration for GPU $GPU_INDEX
# Auto-generated by setup-agent.sh

name="gpu-${GPU_INDEX}-%hostname-%n"
tags="queue=${QUEUE_NAME}"
build-path="/var/lib/buildkite-agent/builds-gpu${GPU_INDEX}"

# Hooks directory (optional)
hooks-path="/etc/buildkite-agent/hooks"

# Plugins directory
plugins-path="/var/lib/buildkite-agent/plugins"

# Disconnect after job (for clean state)
disconnect-after-job=false
disconnect-after-idle-timeout=0

# Enable job log timestamps
timestamp-lines=true
EOF

# Create build directory
mkdir -p "/var/lib/buildkite-agent/builds-gpu${GPU_INDEX}"
chown -R buildkite:buildkite "/var/lib/buildkite-agent/builds-gpu${GPU_INDEX}"

# Create cgroup slice for resource isolation
cat > "/etc/systemd/system/buildkite-gpu${GPU_INDEX}.slice" << EOF
[Unit]
Description=Buildkite Agent Slice for GPU ${GPU_INDEX}
Before=slices.target

[Slice]
MemoryMax=${MEMORY_LIMIT}
CPUQuota=$((CPU_CORES * 100))%
EOF

# Create systemd service for this GPU
cat > "/etc/systemd/system/buildkite-agent-gpu${GPU_INDEX}.service" << EOF
[Unit]
Description=Buildkite Agent for GPU ${GPU_INDEX} (${QUEUE_NAME})
Documentation=https://buildkite.com/docs/agent/v3
After=network.target docker.service
Requires=docker.service

[Service]
Type=simple
User=buildkite
Group=buildkite

# GPU isolation - only this GPU is visible
Environment="CUDA_VISIBLE_DEVICES=${GPU_INDEX}"

# Pass agent token (should be set in environment file)
EnvironmentFile=-/etc/buildkite-agent/token

# Use agent-specific config
ExecStart=/usr/bin/buildkite-agent start --config ${AGENT_CONFIG_DIR}/buildkite-agent.cfg

# Restart on failure
Restart=always
RestartSec=5

# Resource isolation via cgroup slice
Slice=buildkite-gpu${GPU_INDEX}.slice

# Hardening
NoNewPrivileges=false
ProtectSystem=full
ProtectHome=read-only

[Install]
WantedBy=multi-user.target
EOF

# Create environment file for token if it doesn't exist
if [[ ! -f /etc/buildkite-agent/token ]]; then
    cat > /etc/buildkite-agent/token << EOF
# Buildkite agent token - set this to your organization's token
# Get it from: https://buildkite.com/organizations/<org>/agents
BUILDKITE_AGENT_TOKEN=
EOF
    chmod 600 /etc/buildkite-agent/token
    echo ""
    echo "⚠️  IMPORTANT: Set your Buildkite agent token in /etc/buildkite-agent/token"
fi

# Reload systemd and enable the service
systemctl daemon-reload
systemctl enable "buildkite-agent-gpu${GPU_INDEX}.service"

echo ""
echo "✅ Buildkite agent for GPU $GPU_INDEX configured successfully!"
echo ""
echo "Next steps:"
echo "  1. Set BUILDKITE_AGENT_TOKEN in /etc/buildkite-agent/token"
echo "  2. Start the agent: sudo systemctl start buildkite-agent-gpu${GPU_INDEX}"
echo "  3. Check status: sudo systemctl status buildkite-agent-gpu${GPU_INDEX}"
echo "  4. View logs: sudo journalctl -u buildkite-agent-gpu${GPU_INDEX} -f"
echo ""
echo "To set up additional GPUs, run this script with different GPU indices."
